version: "3.9"

services:
  api:
    build: .
    container_name: faceauth-api
    ports:
      - "5000:5000"
    volumes:
      - .:/app    
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload   
    depends_on:
      - mongo 
    environment:
      - MONGO_URI=mongodb://mongo:27017/faceauth
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: faceauth-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
